= SCAMP update

. The problem: distributed agreement
.. Solution: Paxos/Raft protocols
... What it is: Leader election, full cluster membership knowledge required, transactional cluster agreement
... CAP Rating: CA-
... Scalability comments: voting rounds require en masse communication from the leader to all followers (larger cluster = slower voting rounds and increasing liklihood of partitioning)
... When to use Paxos/Raft: if you need Consistency and Availability guarantees and are willing to tolerate downtime in the case of a Partition (network interruption) within the cluster
.. Solution: Gossip protocols
... What it is: the implementation of a metaphor
... CAP Rating: -AP
... Scalability comments: gossip protocols rely on redundant communication, 
. Naive implementation (November, 2015)
.. used TCP for comm, every node had membership list of entire cluster

> He was a scamp; he is a hero!
> - Les Misérables (Signet, p587)



SCAMP = SCAlable Membership Protocol

== Usage

`lein test`

== TODO

. Implement HyParView
. Evaluate results for clumping: https://arxiv.org/pdf/0906.0612.pdf

